### ISSUE TITLE
VPC endpoints and IRSA 

### ISSUE THREAD

**Issue by thewire247** [external-secrets/kubernetes-external-secrets#624]
I have a cluster set up with IRSA to allow pods to assume AWS roles. This works fine in other pods running in the cluster. The cluster is required to access AWS services via VPC endpoints so there are no NAT gateways.

I've deployed the helm chart to the cluster, ensuring I specify the following:

```
customResourceManagerDisabled: true

env:
  AWS_REGION: eu-west-1
  AWS_DEFAULT_REGION: eu-west-1
  POLLER_INTERVAL_MILLISECONDS: 10000  # Caution, setting this frequency may incur additional charges on some platforms
  WATCH_TIMEOUT: 60000
  WATCHED_NAMESPACES: '' # Comma separated list of namespaces, empty or unset means ALL namespaces.
  LOG_LEVEL: info
  LOG_MESSAGE_KEY: 'msg'
  METRICS_PORT: 3001
  VAULT_ADDR: http://127.0.0.1:8200
  AWS_STS_ENDPOINT_TYPE: regional
  AWS_STS_ENDPOINT: https://sts.eu-west-1.amazonaws.com
  AWS_SM_ENDPOINT: https://secretsmanager.eu-west-1.amazonaws.com

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<accountid>:role/rolename
  name: "rolename"

securityContext:
  runAsNonRoot: true
  fsGroup: 65534
```

When launched, the following repeats itself in the logs:

```
{"level":20,"time":1612957723035,"pid":18,"hostname":"kubernetes-external-secrets","msg":"spinning up poller for default/mysecret"}
{"level":30,"time":1612957723038,"pid":18,"hostname":"kubernetes-external-secrets","msg":"starting poller for default/mysecret"}
{"level":20,"time":1612957723047,"pid":18,"hostname":"kubernetes-external-secrets","msg":"next poll for default/mysecret in 0 ms"}
{"level":30,"time":1612957723048,"pid":18,"hostname":"kubernetes-external-secrets","msg":"running poll on the secret default/mysecret"}
{"level":30,"time":1612957723065,"pid":18,"hostname":"kubernetes-external-secrets","msg":"fetching secret property mysecret with role: pods role in region eu-west-1"}
{"level":30,"time":1612957729041,"pid":18,"hostname":"kubernetes-external-secrets","msg":"No watch event for 6000 ms, restarting watcher for *"}
{"level":30,"time":1612957729041,"pid":18,"hostname":"kubernetes-external-secrets","msg":"Stopping watch stream for namespace * due to event: END"}
{"level":20,"time":1612957729041,"pid":18,"hostname":"kubernetes-external-secrets","msg":"Starting watch stream for namespace *"}
{"level":20,"time":1612957729042,"pid":18,"hostname":"kubernetes-external-secrets","msg":"stopping and removing poller d56b8113-7bc8-4d02-9034-87a238455153"}
{"level":30,"time":1612957729042,"pid":18,"hostname":"kubernetes-external-secrets","msg":"stopping poller for default/mysecret"}
```

Eventually I'll get an error that looks like:
```
{"level":50,"time":1612956668492,"pid":17,"hostname":"kubernetes-external-secrets","payload":{"message":"User: arn:aws:sts::<accountid>:assumed-role/myrole/i-xxxxxxxxxxxxx is not authorized to perform: secretsmanager:GetSecretValue on resource: mysecret","code":"AccessDeniedException","time":"2021-02-10T11:31:08.491Z","requestId":"a7197f03-9593-4d7f-ab50-78f0cb302390","statusCode":400,"retryable":false,"retryDelay":20.099203454419467},"msg":"failure while polling the secret default/mysecret"}
{"level":20,"time":1612956668493,"pid":17,"hostname":"kubernetes-external-secrets","msg":"updating status for default/mysecret to: ERROR, User: arn:aws:sts::<accountid>:assumed-role/myrole/i-xxxxxxxxxxxxx is not authorized to perform: secretsmanager:GetSecretValue on resource: mysecret"}
```

It will dump out many of these errors all at once.

**Comment by Flydiverny** [comment]
Not sure if it makes a difference but `AWS_STS_ENDPOINT` and `AWS_SM_ENDPOINT` was not released and is not available in 6.2.0.
I just pushed the 6.3.0 release.

**Comment by thewire247** [comment]
Thanks, I've updated to 6.3.0 and am still getting the same behaviour
